// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialSettings() {
  return window['go']['main']['App']['GetInitialSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SubmitSettings(arg1) {
  return window['go']['main']['App']['SubmitSettings'](arg1);
}
