// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialSettings():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SubmitSettings(arg1:string):Promise<boolean>;
